roleConfig:
  developerRole: frontoffice-dev-contributors
  releaseManagerRole: frontoffice-release-managers
  deploymentManagerRole: frontoffice-deployment-managers
  projectAdminRole: frontoffice-project-admin
  
  
configurableJobSections: 
 scm: GENERIC_SCM_SECTION_CONFIGURER
 trigger: GENERIC_SCM_TRIGGER_SECTION_CONFIGURER
 email: EXTENDED_EMAIL_SECTION_CONFIGURER
 
notificationConfig:   
  defaultRecipientEmailSuffix: -recipients@ibx.com
  defaultEscalationEmailSuffix: -escalations@ibx.com  

viewConfig:
  sectionViews:
    projectDescriptionTemplatePath: resources/generic/section-view-description.template
    
    
buildConfig:
  tools:
    maven:
      name: maven3
      settings: frontoffice-maven-settings
    scm: 
      name: git222
      credentials: STASH_ACCESS
      changeSetUrlPattern: http://${baseStashUrl}/projects/${projectKey}/repos/${repositorySlug}
      releasePushUrlPattern: http://${gitUser}:${gitPassword}@${baseStashUrl}/scm/${projectKey}/${repositorySlug}.git    
    jdk:
      name: jdk8u31
      
      
continuousIntegrationConfig: &continuousIntegrationConfig
  goals: clean install test deploy -P ci
  pollSchedule: 
  jobSuffix: -ci
  generatorClass: com.ibx.frontoffice.jenkins.job.generator.impl.ContinuousIntegrationJobGenerator
  description: The CI job for the repository, fires on every commit to the repository
  
  
codeQualityConfig:
  disabled: false
  goals: findbugs:check checkstype:check pmd:check cobertura:cobertura
  pollSchedule: '@daily'
  jobSuffix: -quality-Tests  
  generatorClass: com.ibx.frontoffice.jenkins.job.generator.impl.CodeQualityJobGenerator
  
  
gitflowFeatureBranchConfig: &gitflowFeatureBranchConfig
  startConfig:
    goals: clean install test jgitflow:feature-start -B -Pgitflow
    goalArgs: {featureName: $featureName, enableFeatureVersions: true}
    jobPrefix: StartFeature_
    projectDescriptionTemplatePath: resources/generic/gitflow-start-feature-description.template
  finishConfig: 
    goals: clean install test jgitflow:feature-finish -B -Pgitflow
    goalArgs: {keepBranch: true,  featureName: $featureName, autoVersionSubmodules: true}
    projectDescriptionTemplatePath: resources/generic/gitflow-finish-feature-description.template
    jobPrefix: FinishFeature_     
  generatorClass: com.ibx.frontoffice.jenkins.job.generator.impl.GitflowFeatureBranchJobGenerator
  
  
gitflowReleaseBranchConfig: &gitflowReleaseBranchConfig
  startConfig:
    goals: clean install test jgitflow:release-start -B -Pgitflow,ci
    goalArgs: {autoVersionSubmodules: true, startCommit: $releaseFromBranch}
    jobPrefix: StartRelease_
    projectDescriptionTemplatePath: resources/generic/gitflow-start-release-description.template
      
  finishConfig:
    goals: clean test jgitflow:release-finish -B -Pgitflow,ci
    goalArgs: {autoVersionSubmodules: true, keepBranch: true, featureName: $featureName}
    jobPrefix: FinishRelease_
    projectDescriptionTemplatePath: resources/generic/gitflow-finish-release-description.template
  generatorClass: com.ibx.frontoffice.jenkins.job.generator.impl.GitflowReleaseBranchJobGenerator
  
  
  
gitflowHotfixBranchConfig: &gitflowHotfixBranchConfig
  startConfig:
    goals: clean install test jgitflow:hotfix-start -B -Pgitflow
    goalArgs:
      autoVersionSubmodules: true
    jobPrefix: StartHotfix_
    projectDescriptionTemplatePath: resources/generic/gitflow-start-hotfix-description.template
  finishConfig:
    goals: clean install test jgitflow:hotfix-finish -B -Pgitflow
    goalArgs:
      autoVersionSubmodules: true
      keepBranch: true
      featureName: $featureName
    jobPrefix: FinishHotfix_
    projectDescriptionTemplatePath: resources/generic/gitflow-finish-hotfix-description.template
  generatorClass: com.ibx.frontoffice.jenkins.job.generator.impl.GitflowHotfixBranchJobGenerator
 
  
  
deploymentConfig: &deploymentConfig
  artifactRepositoryUrl: http://repo.test.ibx.com/
  projectDescriptionTemplatePath: resources/generic/default-deployment-project-description.template
  appConfigurationArtifactIdentificationPattern: .*conf.*
  generatorClass: com.ibx.frontoffice.jenkins.job.generator.impl.DeploymentJobGenerator
  releaseVersionCountToDisplay: 5
  snapshotVersionCountToDisplay: 5
  environments:
    - name: dev
      servers: 1,2,3
    
buildPipelinePreferences:
- branchName: develop
  pipeline:
  - *continuousIntegrationConfig
- branchName: master
  pipeline:
  - *gitflowFeatureBranchConfig
  - *gitflowReleaseBranchConfig
  - *gitflowHotfixBranchConfig
  - *deploymentConfig 
 