roleConfig: 
  developerRole: frontoffice-dev-contributors
  releaseManagerRole: frontoffice-release-managers
  deploymentManagerRole: frontoffice-deployment-managers
  projectAdminRole: frontoffice-project-admin
  
  
configurableJobSections: 
 scm: GENERIC_SCM_SECTION_CONFIGURER
 trigger: GENERIC_SCM_TRIGGER_SECTION_CONFIGURER
 email: EXTENDED_EMAIL_SECTION_CONFIGURER
 maven: MAVEN_SECTION_CONFIGURER

 
notificationConfig:   
  defaultRecipientEmailSuffix: -recipients@ibx.com
  defaultEscalationEmailSuffix: -escalations@ibx.com
    

viewConfig:
  sectionViews:
    projectDescriptionTemplatePath: resources/core/section-view-description.template
    
jobSeederName: frontoffice-repository-branch-job-creator
      
buildConfig:
   maven: 
      name: maven3
      settings: frontoffice-maven-settings 
   scm:  
      name: git222
      credentials: STASH_ACCESS
   languageRuntime: 
        type: java  
        name: jdk8u31
        
healthConfig: &healthConfig
  goals: verify
  jobSuffix: -health
  generatorClass: com.liquidhub.framework.ci.job.generator.impl.BranchHealthMonitor
  description: Monitors the health of the branch. Fails only if the code does not compile and test
  regularEmailRecipients: jenkinssysadmin@ibx.com,fopsateam@ibx.com,frontofficeprojectadmin@ibx.com
        
      
continuousIntegrationConfig: &continuousIntegrationConfig
  goals: deploy -P ci
  pollSchedule: 
  jobSuffix: -ci
  generatorClass: com.liquidhub.framework.ci.job.generator.impl.ContinuousIntegrationJobGenerator
  description: The CI job for the repository, fires on every commit to the repository
  
  
codeQualityConfig:
  disabled: false
  goals: test findbugs:check checkstype:check pmd:check cobertura:cobertura
  pollSchedule: '@daily'
  jobSuffix: -quality-Tests  
  generatorClass: com.ibx.frontoffice.jenkins.job.generator.impl.CodeQualityJobGenerator
  

milestoneReleaseConfig: &milestoneReleaseConfig
  jobPrefix: FinishMilestoneRelease_
  projectDescriptionTemplatePath: resources/core/gitflow-finish-release-description.template  
  generatorClass: com.liquidhub.framework.ci.job.generator.impl.MilestoneReleaseJobGenerator
  activeMavenProfiles: release
  regularEmailRecipients: jenkinssysadmin@ibx.com,fopsateam@ibx.com,frontofficeprojectadmin@ibx.com
  
gitflowFeatureBranchConfig: &gitflowFeatureBranchConfig
  startConfig:
    goals: verify jgitflow:feature-start -B -Pgitflow
    goalArgs: {featureName: $featureName}
    jobPrefix: StartFeature_
    projectDescriptionTemplatePath: resources/core/gitflow-start-feature-description.template
    generatorClass: com.liquidhub.framework.ci.job.generator.impl.GitflowStartFeatureJobGenerator
    emailContent: ${JELLY_SCRIPT, template="frontoffice-feature-start-email-template.jelly"}
    regularEmailRecipients: jenkinssysadmin@ibx.com,fopsateam@ibx.com,frontofficeprojectadmin@ibx.com
  finishConfig: 
    goals: verify jgitflow:feature-finish -B -Pgitflow
    goalArgs: {keepBranch: $keepBranch,  featureName: $featureName, noFeatureMerge: $skipFeatureMergeToDevelop, squash: $squashCommits}
    projectDescriptionTemplatePath: resources/core/gitflow-finish-feature-description.template
    jobPrefix: FinishFeature_
    generatorClass: com.liquidhub.framework.ci.job.generator.impl.GitflowFinishFeatureJobGenerator
    emailContent: ${JELLY_SCRIPT, template="frontoffice-feature-finish-email-template.jelly"}
    regularEmailRecipients: jenkinssysadmin@ibx.com,fopsateam@ibx.com,frontofficeprojectadmin@ibx.com
  
  
gitflowReleaseBranchConfig: &gitflowReleaseBranchConfig
  startConfig:
    goals: verify jgitflow:release-start -B -Pgitflow,ci
    goalArgs: {autoVersionSubmodules: true}
    jobPrefix: StartRelease_
    projectDescriptionTemplatePath: resources/core/gitflow-start-release-description.template
    generatorClass: com.liquidhub.framework.ci.job.generator.impl.GitflowStartReleaseJobGenerator
    emailContent: ${JELLY_SCRIPT, template="frontoffice-release-start-email-template.jelly"}
    regularEmailRecipients: jenkinssysadmin@ibx.com,fopsateam@ibx.com,frontofficeprojectadmin@ibx.com
      
  finishConfig:
    goals: verify jgitflow:release-finish deploy -B
    goalArgs: {autoVersionSubmodules: true}
    jobPrefix: FinishRelease_
    projectDescriptionTemplatePath: resources/core/gitflow-finish-release-description.template
    generatorClass: com.liquidhub.framework.ci.job.generator.impl.GitflowFinishReleaseJobGenerator
    activeMavenProfiles: release,gitflow,ci
    emailContent: ${JELLY_SCRIPT, template="frontoffice-release-finish-email-template.jelly"}
    regularEmailRecipients: jenkinssysadmin@ibx.com,fopsateam@ibx.com,frontofficeprojectadmin@ibx.com
  
  
gitflowHotfixBranchConfig: &gitflowHotfixBranchConfig
  startConfig:
    goals: verify jgitflow:hotfix-start -B -Pgitflow
    goalArgs:
      autoVersionSubmodules: true
    jobPrefix: StartHotfix_
    projectDescriptionTemplatePath: resources/core/gitflow-start-hotfix-description.template
    generatorClass: com.liquidhub.framework.ci.job.generator.impl.GitflowStartHotfixJobGenerator
    regularEmailRecipients: jenkinssysadmin@ibx.com,fopsateam@ibx.com,frontofficeprojectadmin@ibx.com
  finishConfig:
    goals: verify jgitflow:hotfix-finish -B -Pgitflow
    goalArgs:
      autoVersionSubmodules: true
    jobPrefix: FinishHotfix_
    projectDescriptionTemplatePath: resources/core/gitflow-finish-hotfix-description.template
    generatorClass: com.liquidhub.framework.ci.job.generator.impl.GitflowFinishHotfixJobGenerator
    regularEmailRecipients: jenkinssysadmin@ibx.com,fopsateam@ibx.com,frontofficeprojectadmin@ibx.com
    activeMavenProfiles: release
  
  
deploymentConfig: &deploymentConfig
  artifactRepositoryUrl: http://repo.ibx.com/
  serverTemplate: WEBSPHERE
  artifactRepository: NEXUS
  appConfigurationArtifactIdentificationPattern: .*conf.*
  jobSuffix: Deployer
  generatorClass: com.liquidhub.framework.ci.job.generator.impl.DeploymentJobGenerator
  releaseVersionCountToDisplay: 5
  snapshotVersionCountToDisplay: 5
  deploymentScriptPath: resources/core/default-deployment-script.sh
  regularEmailRecipients: jenkinssysadmin@ibx.com,frontofficeprojectadmin@ibx.com
       
buildDiscardPolicy: 
  daysToKeep: 7
  numToKeep: 7
  artifactDaysToKeep: 7
  artifactNumToKeep: 7
    
buildPipelinePreferences:
- branchName: develop
  pipeline:
  - *continuousIntegrationConfig
 
- branchName: master
  pipeline:
  - *gitflowFeatureBranchConfig
  - *gitflowReleaseBranchConfig
  - *gitflowHotfixBranchConfig
  - *milestoneReleaseConfig
  - *deploymentConfig
  - *healthConfig  

 